name: Alias

default_ecosystem: ethereum

contracts_folder: contracts

plugins:
  - name: solidity
    version: 0.6.3

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.3

solidity: 
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.8.3"

